In [ ]:
import numpy as np

In [ ]:
### Create an array

In [ ]:
a1 = np.array([12,31,4,2,2,345,1,3])  # 1d array
a2 = np.array([[12,31,4,2,2,345,1,3]])  # 2d array
a3 = np.array([[12,31,4,2,2,345,1,3],[12,31,4,2,2,345,1,3]])  # 2d array
a4 = np.array([[[12,31,4,2,2,345,1,3],[12,31,4,2,2,345,1,3]]])  # 3d array
a5 = np.array([[[12,31,4,2,2,345,1,3],[12,31,4,2,2,345,1,3]],
               [[12,31,4,2,2,345,1,3],[12,31,4,2,2,345,1,3]]])  # 3d array

In [ ]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

8
1
2
1
2


In [ ]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)
print(a5.ndim)

1
2
2
3
3


In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

int64
int64
int64
int64
int64


In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)

(8,)
(1, 8)
(2, 8)
(1, 2, 8)
(2, 2, 8)


In [ ]:
r1 = np.random.randint(100) # 1 random no b/w 0 to 99
r1

34

In [ ]:
r1 = np.random.randint(100,500) # 1 random no b/w 100 to 499
r1

476

In [ ]:
r1 = np.random.randint(100,500,10) # 10 random nos b/w 100 to 499
r1

array([372, 143, 426, 200, 154, 156, 275, 483, 203, 312])

In [ ]:
r1 = np.random.randint(100,500,(5,2)) # 10 random nos b/w 100 to 499
r1

array([[275, 269],
       [262, 110],
       [151, 419],
       [121, 157],
       [123, 146]])

In [1]:
r1 = np.random.randint(100,500,(5,2,1)) # 10 random nos b/w 100 to 499
r1

NameError: ignored

In [ ]:
# seed in random

In [ ]:
np.random.seed(10)
r1 = np.random.randint(100) # 1 random no b/w 0 to 99
r1

9

In [ ]:
# Array Indexing and Slicing

In [ ]:
np.random.seed(10)
r1 = np.random.randint(100,500,(8,10)) # 1 random no b/w 0 to 99
r1

array([[365, 225, 115, 420, 469, 223, 256, 321, 469, 108],
       [173, 356, 140, 471, 116, 456, 339, 495, 154, 444],
       [463, 222, 162, 133, 300, 456, 277, 279, 154, 177],
       [113, 343, 482, 241, 448, 442, 386, 258, 189, 240],
       [421, 131, 413, 392, 383, 118, 193, 177, 194, 348],
       [495, 256, 174, 316, 493, 115, 118, 218, 171, 444],
       [495, 245, 235, 303, 384, 389, 350, 452, 144, 233],
       [104, 171, 444, 444, 406, 464, 282, 390, 460, 371]])

In [ ]:
r1[3]

array([113, 343, 482, 241, 448, 442, 386, 258, 189, 240])

In [ ]:
r1[-4]

array([421, 131, 413, 392, 383, 118, 193, 177, 194, 348])

In [ ]:
r1[7][4]

406

In [ ]:
r1[7,4]

406

In [ ]:
r1[2:5]

array([[463, 222, 162, 133, 300, 456, 277, 279, 154, 177],
       [113, 343, 482, 241, 448, 442, 386, 258, 189, 240],
       [421, 131, 413, 392, 383, 118, 193, 177, 194, 348]])

In [ ]:
r1[2:]

array([[463, 222, 162, 133, 300, 456, 277, 279, 154, 177],
       [113, 343, 482, 241, 448, 442, 386, 258, 189, 240],
       [421, 131, 413, 392, 383, 118, 193, 177, 194, 348],
       [495, 256, 174, 316, 493, 115, 118, 218, 171, 444],
       [495, 245, 235, 303, 384, 389, 350, 452, 144, 233],
       [104, 171, 444, 444, 406, 464, 282, 390, 460, 371]])

In [ ]:
r1[0:5]

array([[365, 225, 115, 420, 469, 223, 256, 321, 469, 108],
       [173, 356, 140, 471, 116, 456, 339, 495, 154, 444],
       [463, 222, 162, 133, 300, 456, 277, 279, 154, 177],
       [113, 343, 482, 241, 448, 442, 386, 258, 189, 240],
       [421, 131, 413, 392, 383, 118, 193, 177, 194, 348]])

In [ ]:
r1[2:5,3:6]

array([[133, 300, 456],
       [241, 448, 442],
       [392, 383, 118]])

In [ ]:
print(np.max(r1))
print(np.max(r1,axis=0)) #row
print(np.max(r1,axis=1)) #column

495
[495 356 482 471 493 464 386 495 469 444]
[469 495 463 482 421 495 495 464]


In [ ]:
print(np.min(r1))
print(np.min(r1,axis=0)) #row
print(np.min(r1,axis=1)) #column

104
[104 131 115 133 116 115 118 177 144 108]
[108 116 133 113 118 115 144 104]


In [ ]:
print(np.mean(r1))
print(np.mean(r1,axis=0)) #row
print(np.mean(r1,axis=1)) #column

302.7
[328.625 243.625 270.625 340.    374.875 332.875 275.125 323.75  241.875
 295.625]
[297.1 314.4 262.3 314.2 277.  280.  323.  353.6]


In [ ]:
print(np.sum(r1))
print(np.sum(r1,axis=0)) #row
print(np.sum(r1,axis=1)) #column

24216
[2629 1949 2165 2720 2999 2663 2201 2590 1935 2365]
[2971 3144 2623 3142 2770 2800 3230 3536]


In [ ]:
print(np.argmax(r1))
print(np.argmax(r1,axis=0)) #row
print(np.argmax(r1,axis=1)) #column

17
[5 1 3 1 5 7 3 1 0 1]
[4 7 0 2 0 0 0 5]


In [ ]:
print(np.argmin(r1))
print(np.argmin(r1,axis=0)) #row
print(np.argmin(r1,axis=1)) #column

70
[7 4 0 2 1 5 5 4 6 0]
[9 4 3 0 5 5 8 0]


In [ ]:
# change shape of array

In [ ]:
r1.shape

(8, 10)

In [ ]:
r1_1 = r1.reshape(80) #1d
r1_1

array([365, 225, 115, 420, 469, 223, 256, 321, 469, 108, 173, 356, 140,
       471, 116, 456, 339, 495, 154, 444, 463, 222, 162, 133, 300, 456,
       277, 279, 154, 177, 113, 343, 482, 241, 448, 442, 386, 258, 189,
       240, 421, 131, 413, 392, 383, 118, 193, 177, 194, 348, 495, 256,
       174, 316, 493, 115, 118, 218, 171, 444, 495, 245, 235, 303, 384,
       389, 350, 452, 144, 233, 104, 171, 444, 444, 406, 464, 282, 390,
       460, 371])

In [ ]:
r1_1 = r1.reshape(20,4) #1d
r1_1

array([[365, 225, 115, 420],
       [469, 223, 256, 321],
       [469, 108, 173, 356],
       [140, 471, 116, 456],
       [339, 495, 154, 444],
       [463, 222, 162, 133],
       [300, 456, 277, 279],
       [154, 177, 113, 343],
       [482, 241, 448, 442],
       [386, 258, 189, 240],
       [421, 131, 413, 392],
       [383, 118, 193, 177],
       [194, 348, 495, 256],
       [174, 316, 493, 115],
       [118, 218, 171, 444],
       [495, 245, 235, 303],
       [384, 389, 350, 452],
       [144, 233, 104, 171],
       [444, 444, 406, 464],
       [282, 390, 460, 371]])

In [ ]:
## Array operations

In [ ]:
x = np.array([10,20,30])
y = np.array([100,200,300])
op1 = np.add(x,y)
op2 = np.subtract(x,y)
op3 = np.multiply(x,y)
op4 = np.divide(x,y)
op5 = np.dot(x,y)

In [ ]:
op1

array([110, 220, 330])

In [ ]:
op2

array([ -90, -180, -270])

In [ ]:
op3

array([1000, 4000, 9000])

In [ ]:
op4

array([0.1, 0.1, 0.1])

In [ ]:
op5

14000

In [2]:
x = np.array([[10,20,30],[10,20,30]])
y = np.array([[100,200,300,400],[100,200,300,400]])
print(x)
print(y)

NameError: ignored

In [ ]:
np.dot(x.T,y)

array([[ 2000,  4000,  6000,  8000],
       [ 4000,  8000, 12000, 16000],
       [ 6000, 12000, 18000, 24000]])